# Generated by Django 4.2 on 2023-04-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=25),
        ),
    ]
